#1. Ստեղծեք Calculation class

In [5]:
class calculation:
    def __init__(self, x, y):
        self.x=x
        self.y=y
    def addition(self):
        print('x+y',self.x+self.y)
    def subtract(self):
        print('x-y=',self.x-self.y)
a=calculation(12,24)
a.addition()
class MyCalculation(calculation):
    def __init__(self,x,y):
        calculation.__init__(self,x,y)
    def multiple(self):
        print('x*y=',self.x*self.y)
    def division(self) :
b        print(self.x/self.y)
b=MyCalculation(34,0)   
b.multiple()
b.division()  

x+y 36
x*y= 0


AssertionError: give other numers

#2

In [8]:
class My_Time:
    def __init__(self,t):
        self.t=t
       
    def printTime(self):
        print('The current time is',self.t)
       
class     MY_Date():
        def __init__(self,d):
            self.d=d
            
           
        def printDate(self):
            print('The current date is',self.d)
          
       
class Date_Time(My_Time,MY_Date):
    def __init__(self,d,t):
        My_Time.__init__(self,t)
        MY_Date.__init__(self,d)
      
dat=Date_Time('23.03.2013','12.AM')   
dat.printTime()
dat.printDate()
            

    
    

The current time is 12.AM
The current date is 23.03.2013


#3Numpy

In [9]:
import numpy as np
rd=np.random.randint(1,10,(3,5))
rd

array([[5, 5, 6, 7, 7],
       [1, 7, 8, 6, 9],
       [9, 7, 2, 4, 1]])

In [13]:
zer=np.zeros(10,dtype=int)
zer[3]=5
zer

array([0, 0, 0, 5, 0, 0, 0, 0, 0, 0])

In [15]:
num=np.arange(3,16)
num

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [26]:
init=np.arange(1,7)
#init.shape=(3,2)
s=init.reshape(2,3)
d=init.reshape(3,2)
s

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
a=np.arange(5,15)
print(a.mean())
b=np.array([2])
def nparray(data):
    while data.mean()>=5:
        data=np.divide(data,b)
    return data
nparray(a)


    

9.5


array([2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ])

In [32]:
a=np.random.randint(1,10,(5,4))
a

array([[1, 9, 1, 5],
       [4, 2, 4, 9],
       [6, 6, 2, 7],
       [2, 3, 5, 8],
       [4, 6, 8, 5]])

In [36]:
def parser(a):
    return a[0,...],a[1,...],a[2,...],a[3,...],a[4,...]
parser(a)

(array([1, 9, 1, 5]),
 array([4, 2, 4, 9]),
 array([6, 6, 2, 7]),
 array([2, 3, 5, 8]),
 array([4, 6, 8, 5]))